services:
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    depends_on:
      - redis
      - producer
    ports:
      - "${LOCAL_PORT}:${LOCAL_PORT}"
    environment:
      - REDIS_HOST=redis